---
users_for_role:
  admin: [ dawg, sebastian, vladimir ]

user_details:
  dawg:
    name: Martin Nowak
    public_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHMJrET+g/ONsSbjYGNfuk2GRk06ZlBhmypcajwA2jjQ dawg@FedoraX64
    passwd: '$6$P30In2m4T3agNtgY$drj40eagBBsU5EmAZMU00dhcTN.OuX2Xxa//sYfH5P3ISIFhIftsOXQfmiUTGB1UNOoRDTYUo/zEXzYfULy5o0'

  sebastian:
    name: Sebastian Wilzbach
    public_keys: |
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDGn4PHb0levuqcYFsYHzg2oK6RyHQcsq+EPEGjBR2Kaipxyc6XspZGZPkkAJwilNk/8bLAUgaB6bXHBGTShDMU0+s/g6B5plR7RT5m3aw7WYKSC/CgeGLy/PixWWi10/um2XZX7Pj/m4s4edL9fbJY8TRgOx0BooIJbGpEoXZrh8fQQSRescOXeUjzz/yj1ArCtUwHK4VirxiVAK/CiwH3Qng0Jvc0elWNb+/2kYIs4FjJqUOY+J9+dHST4PqaC5jZUj8R2bIP2jm7QnS35hH/lfp/Qz0yrlH6vGlF90kNdFSlU6u5HFtkq3X5lH2Ulowk/Eclmkqabqd59U5dZN6ZXMMFjOpEXC07HFC8GVHrwjDqZKc13FdQaUqLv4MTS4o1OCJAA20QVCdlw7tl/Qhc9GQhTtCliXIilXKWDxYSrVUcXQQs+tT+mafVY7GI5RSC9qWVR5ELMxftr1/RgjdfQXeLRuiGu5u0X2G7Sni8k7BonLegKnd41PEL3nw99R3aBkzYs9g9hWie0zjgTQBjGGE3HTmnrTlTXzVGNu1vEogHW2wzlwsOeaTGuggVxvHGW1aQ8SNOREui79ETr16Kwj6qBKTu4u++bBYsHnjJ1nDHLlS1XuHDznjbzn/PN1smOBklD3mi9alN2mmYf3ca/nBXsN2iOdlPwdcDVbVU+Q== wilzbach@github.com
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC5TAgJCiF8d23i+yd2CBzPaPiauFxBB922WE8CtsVel9yagiTSR3kxsM8dY8KlWUhHmyb2RBhYpB895HJ3hcmIOptifp4vZtDxGIXWo/R0El64li5yqFqJA8EnPUwz2RnaWf5nP46fPpmWd8XS6EBbILif2Lmv8Qn4TpWtA2qdx42ljkyvyTPAO44H1zj3UeSbNtX9bCPCIKAevveHCk1r59ut7sYR6Tsf7z4Wbtd7zXqgxQM7fCq+zEnNL54dAzAT5XUGlmcNSm6V16/qO8vPOszdmVekJaq+WET4RngL5Z1SKNKgrSiIvIEHP1kuYd5CRMzQ0K5jaJMvE93a/2HvmAKW/kUfOmig1n5X7LY2WMrjoy6mWqtOWAAXvCco17QjjNK68U1O6l3GcYW0+IW4r8kFGTna+YocwJwZAhwo0HwiqZGkwyb77d53x60ccvsI8iX2k/tPk8e7uyxdngUJVrkOi6vX9L0CDVy7yYfWLWUWGNNd8e5OcvxfOEikfmBLqVlUSx2hBrqRw09nnKXR+cjVnk3HGjfk5l6Or8W5BeBTRFndiuQbldYl4rl+aLi/XFpYucJHb/V2ypoKITHQqkBJr3Bqb4MCZnGUm64ElwbaakgxqTv7mBGD8V5rm7VeRuwBPaGBWK1sPPYNCK+ubMYkR64sEC8N6z2y7otJSw== wilzbach@github.com
    passwd: '$6$VRvEnV5bsK9GvBIp$waySCZ9OEW7M83eiPFyCabzjgKYBjRRAoXnajHCWvZL95wNFvsxIGM7cPt0837oZ2BDAo/w.gC3CJZrWsC8um/'

  vladimir:
    name: Vladimir Panteleev
    public_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIXBZbDe5iEyjpez3DFZunviovPqkCoTjrqLTuOUk6Le vladimir@home.thecybershadow.net
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDWg6h5HHh++C6KaTjW6Z0Y3QHa1z+3srNtOi/Y+AeMC vladimir@vaio.thecybershadow.net
    passwd: '*'

  # keep removed accounts with state absent to actually delete them on servers
