---
- name: systemctl daemon-reload
  systemd: { daemon_reload: yes }
- name: restart buildkite-agent
  service: { name: buildkite-agent, state: restarted }
- name: restart agent-shutdown-check.timer
  systemd: { name: agent-shutdown-check.timer, state: restarted }
